### ISSUE TITLE
Failed with missing cairo.h (libxputty)

### ISSUE THREAD

**Issue by slangbein** [brummer10/CollisionDrive#1]
Linux Mint 20.2
libcairo2-dev installed version 1.16.0-4ubuntu1
make fails with
../libxputty/libxputty/include/xputty.h:35:10: fatal error: cairo.h: File not found
the file is in /usr/include/cairo/cairo.h
so i guess, this error relates to libxputty and pkgconfig?

**Comment by brummer10** [comment]
what did you get when running 
`pkg-config --cflags --libs cairo`

**Comment by slangbein** [comment]
result: -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -lcairo

**Comment by brummer10** [comment]
So it _should_ work. I've no idea what could goes wrong here.

**Comment by slangbein** [comment]
Hm, google says there should be a file xputty.pc in /usr/local/lib/pkgconfig/
make message before the error:
Package xputty was not found in the pkg-config search path.
Perhaps you should add the directory containing `xputty.pc'
to the PKG_CONFIG_PATH environment variable
No package 'xputty' found
Package lilv-0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lilv-0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lilv-0' found

**Comment by brummer10** [comment]
Ah, I see, my fool. 
I've libxputty installed, so I didn't noticed that I've enabled the wrong line in the makefile which use my local installed libxputty. 
I hope the last commit fix it.

**Comment by slangbein** [comment]
yes, working now:-)

**Comment by brummer10** [comment]
Nice, thanks for reporting the issue and confirm the Fix. I'll close the issue now.
